require: standard
inherit_gem:
  standard: config/base.yml
AllCops:
  TargetRubyVersion: 3.4
  Exclude:
    - "vendor/bundle/**/*"
    - "tmp/**/*"
    - "public/**/*"
    - "bin/{bundle,rails,rake,spring}"
