name: "CI"
on:
  pull_request:
  push:
    branches: [ main ]
jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    permissions:
      contents: read
      issues: read
      checks: write
      pull-requests: write
    env:
      RAILS_ENV: test
    steps:
      - name: Checkout code
        uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8
      - name: Install Ruby and gems
        uses: ruby/setup-ruby@03b78bdda287ae04217ee12e4b64996630a03542
        with:
          bundler-cache: true
          cache-version: ruby-${{ hashFiles('Gemfile.lock') }}
      - name: Run RSpec Tests
        timeout-minutes: 20
        run: bundle exec rspec
  lint:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    permissions:
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8
      - name: Install Ruby and gems
        uses: ruby/setup-ruby@03b78bdda287ae04217ee12e4b64996630a03542
        with:
          bundler-cache: true
          cache-version: ruby-${{ hashFiles('Gemfile.lock') }}
      - name: Bundle Audit Check
        run: bundle exec bundle-audit update && bundle exec bundle-audit check
      - name: Setup Python
        uses: actions/setup-python@2c3dd9e7e29afd70cc0950079bde6c979d1f69f9
      - name: Run pre-commit
        continue-on-error: true
        uses: pre-commit/action@4835dd97624f38176d7f9f87fcce089836248ee9
