name: Pull Request Updated

on:
  pull_request:
    types:
      - opened
      - reopened
      - edited
      - synchronize
      - ready_for_review
      - converted_to_draft

jobs:
  tag-libero-for-dependabot:
    name: Tag Libero For Dependabot
    if: ${{ github.actor == 'dependabot[bot]' }}
    runs-on: ubuntu-24.04
    timeout-minutes: 2
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Generate a token
        id: generate_token
        uses: actions/create-github-app-token@v2
        with:
          app-id: ${{ secrets.DEPENDABOT_AUTO_MERGER_APP_ID }}
          private-key: ${{ secrets.DEPENDABOT_AUTO_MERGER_PRIVATE_KEY }}
          owner: ${{ github.repository_owner }}
          repositories: ${{ github.event.repository.name }}
      - name: Auto Assign libero for reviewer
        run: gh pr edit "$PR_URL" --add-reviewer "$REVIEWER"
        env:
          PR_URL: ${{ github.event.pull_request.html_url }}
          REVIEWER: instrumentl/libero
          GITHUB_TOKEN: ${{ steps.generate_token.outputs.token }}
          GH_REPO: ${{ github.repository }}
